### PR TITLE
add new uos-public rosinstall for indigo

### PR DESCRIPTION
**Pull request by v4hn**

### CODE REVIEW

**Comment by mintar** [comment]
I'd suggest adding `.git` to those uris that don't have it yet. I know it works because GitHub does some clever forwarding, but let's unify it.

Also, please add `uos_rotunit`.

Other than that, the PR looks good to me. The original idea behind the `uos-public-*` files was that they only contain "uos-ros-pkg" things, and that everything else goes into "thirdparty-*", but I didn't fully comply with that myself, so I'm fine with changing this.

**Comment by v4hn** [comment]
On Fri, Apr 17, 2015 at 07:41:30AM -0700, Martin Günther wrote:
> I'd suggest adding `.git` to those uris that don't have it yet. I know it works because GitHub does some clever forwarding, but let's unify it.

/me hands @mintar, @jochensp and @hdeeken plastic swords.
Please fight this out. I don't care at all, but I've heard different opinions on that more than twice now.

> Also, please add `uos_rotunit`.

done

**Comment by jspricke** [comment]
Let's vote. I don't see a reason for the `.git`. You don't add a `index.html` to every toplevel domain aswell, right?

**Comment by hdeeken** [comment]
Uh yeah democracy! I give my vote to NO .git, and totally follow @jspricke's argument!

btw thx @v4hn for making the effort! ;)

**Comment by mintar** [comment]
OK, then let's do that. @v4hn, could you remove the remaining .gits and
squash it? Then let's merge.

**Comment by v4hn** [comment]
On Sat, Apr 18, 2015 at 12:49:43AM -0700, Martin Günther wrote:
> OK, then let's do that. @v4hn, could you remove the remaining .gits and
> squash it? Then let's merge.

@mintar: done

**Comment by jspricke** [comment]
you forgot to squash ;).

**Comment by v4hn** [comment]
On Sat, Apr 18, 2015 at 03:53:50AM -0700, Jochen Sprickerhof wrote:
> you forgot to squash ;).

No, actually I split those up intentionally.
Now, it's adjusted as you requested *bows*.

**Comment by jspricke** [comment]
No need to be that picky on a new file ;).

**Pull request merged**
